name: desafio-backend

services:
  database:
    env_file: .env
    image: bitnami/postgresql # imagem do postgres bem pequena
    ports:
      - ${DB_PORT}:5432
    expose:
      - 5432
    volumes:
      - storage_db:/var/lib/postgres/data
    environment:
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}

volumes:
  storage_db:
